### ISSUE TITLE
Reference ip is not defined

### ISSUE THREAD

**Issue by sts098** [rstrouse/relayEquipmentManager#77]
Not sure what I am doing wrong.  Installed REM on a Raspberry Pi5.  I get an error:

/home/rem/relayEquipmentManager/node_modules/node-ssdp/lib/server.js:33
    var _ip = ip.address()
              ^
ReferenceError: ip is not defined
    at SsdpServer.start (/home/rem/relayEquipmentManager/node_modules/node-ssdp/lib/server.js:33:15)
    at SsdpServer.init (/home/rem/relayEquipmentManager/web/Server.ts:335:25)
    at WebServer.init (/home/rem/relayEquipmentManager/web/Server.ts:51:21)
    at /home/rem/relayEquipmentManager/app.ts:20:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

I set ssdp enabled to false, and REM operates, I can get to the web interface, etc.  But NodeJS Pool Controller seems to need SSDP for it to work.  (NodeJS Pool Controller is actually loaded on a VM).  

Any ideas what I might have done wrong?

**Comment by rstrouse** [comment]
In the config.json file disable the SSDP by setting the "enabled" leaf to false
